### ISSUE TITLE
Add Github Workflow

### ISSUE THREAD

**Issue by RawEnchilada** [BME-MIT-IET/iet-hf-2023-minek#4]

**Comment by fogleins** [comment]
Completed as of https://github.com/BME-MIT-IET/iet-hf-2023-minek/commit/697c87934e293575ea2f8c3c676841166a381e33

**Comment by fogleins** [comment]
Documentation was added with commit https://github.com/BME-MIT-IET/iet-hf-2023-minek/commit/6bdb1fa935f8830b8c4a5d3f9329810331ebb695
