### ISSUE TITLE
Nem-funkcionális jellemzők vizsgálata

### ISSUE THREAD

**Issue by LeventeFarkashazi** [BME-MIT-IET/iet-hf-2023-minek#8]
Vizsgálandó tényezők: biztonság, használhatóság, karbantarthatóság, hordozhatóság, teljesítmény.

**Comment by fogleins** [comment]
A biztonságra és teljesítményre vonatkozó rész a https://github.com/BME-MIT-IET/iet-hf-2023-minek/pull/17-es PR-ben hozzáadva.
A használhatósághoz készült leírás pedig a https://github.com/BME-MIT-IET/iet-hf-2023-minek/pull/19-es PR-ben került hozzáadásra.

**Comment by behappiness** [comment]
A karbantarthatósághoz készült leírás a #23 PR-ben került hozzáadásra.

**Comment by behappiness** [comment]
Minden leírás elkészült.
